name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: update a comment with size
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues/1/comments \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "body": "A comment from **${{ github.workflow }}**."
          }'

    #- uses: edyoung/docker-image-size-action@master
    #  with:
    #    image-name: 'my-image-name'
    #    repo-token: ${{ secrets.GITHUB_TOKEN }}